/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSimulationsRouteImport } from './routes/_auth.simulations'
import { Route as AuthQuizRouteImport } from './routes/_auth.quiz'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthLibraryRouteImport } from './routes/_auth.library'
import { Route as AuthLeaderboardRouteImport } from './routes/_auth.leaderboard'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthSimulationsIdRouteImport } from './routes/_auth.simulations.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSimulationsRoute = AuthSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuizRoute = AuthQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryRoute = AuthLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLeaderboardRoute = AuthLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSimulationsIdRoute = AuthSimulationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthSimulationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthAdminRoute
  '/dashboard': typeof AuthDashboardRoute
  '/leaderboard': typeof AuthLeaderboardRoute
  '/library': typeof AuthLibraryRoute
  '/profile': typeof AuthProfileRoute
  '/quiz': typeof AuthQuizRoute
  '/simulations': typeof AuthSimulationsRouteWithChildren
  '/simulations/$id': typeof AuthSimulationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthAdminRoute
  '/dashboard': typeof AuthDashboardRoute
  '/leaderboard': typeof AuthLeaderboardRoute
  '/library': typeof AuthLibraryRoute
  '/profile': typeof AuthProfileRoute
  '/quiz': typeof AuthQuizRoute
  '/simulations': typeof AuthSimulationsRouteWithChildren
  '/simulations/$id': typeof AuthSimulationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/leaderboard': typeof AuthLeaderboardRoute
  '/_auth/library': typeof AuthLibraryRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/quiz': typeof AuthQuizRoute
  '/_auth/simulations': typeof AuthSimulationsRouteWithChildren
  '/_auth/simulations/$id': typeof AuthSimulationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/library'
    | '/profile'
    | '/quiz'
    | '/simulations'
    | '/simulations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/library'
    | '/profile'
    | '/quiz'
    | '/simulations'
    | '/simulations/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/admin'
    | '/_auth/dashboard'
    | '/_auth/leaderboard'
    | '/_auth/library'
    | '/_auth/profile'
    | '/_auth/quiz'
    | '/_auth/simulations'
    | '/_auth/simulations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/simulations': {
      id: '/_auth/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof AuthSimulationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quiz': {
      id: '/_auth/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthQuizRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library': {
      id: '/_auth/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthLibraryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/leaderboard': {
      id: '/_auth/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthLeaderboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/simulations/$id': {
      id: '/_auth/simulations/$id'
      path: '/$id'
      fullPath: '/simulations/$id'
      preLoaderRoute: typeof AuthSimulationsIdRouteImport
      parentRoute: typeof AuthSimulationsRoute
    }
  }
}

interface AuthSimulationsRouteChildren {
  AuthSimulationsIdRoute: typeof AuthSimulationsIdRoute
}

const AuthSimulationsRouteChildren: AuthSimulationsRouteChildren = {
  AuthSimulationsIdRoute: AuthSimulationsIdRoute,
}

const AuthSimulationsRouteWithChildren = AuthSimulationsRoute._addFileChildren(
  AuthSimulationsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLeaderboardRoute: typeof AuthLeaderboardRoute
  AuthLibraryRoute: typeof AuthLibraryRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthQuizRoute: typeof AuthQuizRoute
  AuthSimulationsRoute: typeof AuthSimulationsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLeaderboardRoute: AuthLeaderboardRoute,
  AuthLibraryRoute: AuthLibraryRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthQuizRoute: AuthQuizRoute,
  AuthSimulationsRoute: AuthSimulationsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
